# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Zachary Lopez
tagline:             Software Engineer
description:         'The thoughts, musings, and projects of a software engineer.'
url:                 http://www.zdlopez.com
baseurl:             /
paginate:            5
excerpt_separator:   <!--more-->

# About/contact
author:
  name:              Zachary Lopez
  url:               https://twitter.com/zdlopez
  email:             zachary.d.lopez@gmail.com

# Custom vars
version:             1.0.0
