title: Zachary Lopez
author: Zachary Lopez
description: "Thoughts, musings, and projects of a full stack engineer."
#subheading: "Really cool blog about ... something"
more: "continue reading"
url: "http://zdlopez.com"
#baseurl: "/"
#baseurl: "/contrast" # comment out if in root directory

comments:
    disqus: "zdlopez"
#    isso: "comments.mysite.org"

style:
#    body: "whitesmoke"
    padding: 33%
    anchor: "#46f"
    serif-heading: true
    nav: "#181818"
#    headline: "#06f"
    description: "white"
    article:
        odd: "#ffffff"
        even: "#222222"

links:
  - github: "https://github.com/zdlopez"
  - twitter: "https://twitter.com/zdlopez"
  - linkedin: "https://linkedin.com/in/zacharylopez"

paginate: 5
excerpt_separator: "<!--more-->"
defaults: [{scope: {path: ""}, values: {layout: "default"}}, {scope: {path: "", type: "posts"}, values: {comments: true}}]
