# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Zachary Lopez
tagline:          Javascript Engineer
url:              http://zdlopez.github.io
paginate:         1
baseurl:          /
author:
  name:           Zachary Lopez
  url:            https://twitter.com/zdlopez
  email:          zachary.d.lopez@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole
